# This file was generated by nvfetcher, please do not modify it manually.
{ fetchFromGitHub, dockerTools }:
{
  mcp-hub = {
    pname = "mcp-hub";
    version = "v1.8.1";
    src = fetchFromGitHub {
      owner = "ravitemer";
      repo = "mcp-hub";
      rev = "v1.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-urFu1xoxeDVCBtYhrQrijL5uuke5XxkaM2CF5IO9kHo=";
    };
  };
}
